ci: fix `build-log` path

diff --git a/release-to-candidate/action.yaml b/release-to-candidate/action.yaml
--- a/release-to-candidate/action.yaml
+++ b/release-to-candidate/action.yaml
@@ -134,7 +134,7 @@ runs:
         snapcraft remote-build ${snapcraft_args[@]} || true
 
         # shellcheck disable=SC2086
-        cat ${name}_${arch}*.txt || echo "Could not find build log"
+        cat snapcraft-${name}*${arch}*.txt || echo "Could not find build log"
 
         if [[ ! -e "${name}_${version}_${arch}.snap" ]]; then
             echo "Could not find ${name}_${version}_${arch}.snap"
