Support for default and custom paths
Path support added for
1. snapcraft.yaml
2. custom-path
3. build-aux/snap/snapcraft.yaml
4. .snapcraft.yaml

diff --git a/sync-version/action.yaml b/sync-version/action.yaml
--- a/sync-version/action.yaml
+++ b/sync-version/action.yaml
@@ -12,6 +12,9 @@ inputs:
   token:
     required: true
     description: A token with write privileges to the repository.
+  yaml-path:
+    description: "Custom path to snapcraft.yaml allowing to have multiple manifests in one repo."
+    required: false
 
 runs:
   using: composite
@@ -39,7 +42,21 @@ runs:
       env:
         SNAP_NAME: ${{ github.event.repository.name }}
       run: |
-        version="$(cat snap/snapcraft.yaml | yq -r '.version')"
+        if [ -n "${{ inputs.yaml-path }}" ]; then
+            yaml_path="${{ inputs.yaml-path }}"
+        elif [ -e snap/snapcraft.yaml ]; then
+            yaml_path="snap/snapcraft.yaml"
+        elif [ -e snapcraft.yaml ]; then
+            yaml_path="snapcraft.yaml"
+        elif [ -e build-aux/snap/snapcraft.yaml ]; then
+            yaml_path="build_aux/snap/snapcraft.yaml"
+        elif [ -e .snapcraft.yaml ]; then
+            yaml_path=.snapcraft.yaml
+        else
+            echo "Could not find snapcraft.yaml"
+            exit 1
+        fi
+        version="$(cat $yaml_path | yq -r '.version')"
         git config --global user.name 'Snapcrafters Bot'
         git config --global user.email 'merlijn.sebrechts+snapcrafters-bot@gmail.com'
         git commit -am "chore: bump ${SNAP_NAME} to version $version"
